/*
 * DEV API (beta)
 *
 * Access DEV articles, comments and other resources via API
 *
 * API version: 0.5.9
 * Contact: yo@dev.to
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package devto

// WebhookCreateWebhookEndpoint struct for WebhookCreateWebhookEndpoint
type WebhookCreateWebhookEndpoint struct {
	// The name of the requester, eg. \"DEV\"
	Source    string `json:"source"`
	TargetUrl string `json:"target_url"`
	// An array of events identifiers
	Events []string `json:"events"`
}
