/*
 * DEV API (beta)
 *
 * Access DEV articles, comments and other resources via API
 *
 * API version: 0.5.9
 * Contact: yo@dev.to
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package devto

// ApiError struct for ApiError
type ApiError struct {
	Error  string `json:"error"`
	Status int32  `json:"status"`
}
