/*
 * DEV API (beta)
 *
 * Access DEV articles, comments and other resources via API
 *
 * API version: 0.5.9
 * Contact: yo@dev.to
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package devto
import (
	"time"
)
// WebhookShow Webhook
type WebhookShow struct {
	TypeOf string `json:"type_of,omitempty"`
	Id int64 `json:"id,omitempty"`
	// The name of the requester, eg. \"DEV\"
	Source string `json:"source,omitempty"`
	TargetUrl string `json:"target_url,omitempty"`
	// An array of events identifiers
	Events []string `json:"events,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	User ArticleUser `json:"user,omitempty"`
}
