/*
 * DEV API (beta)
 *
 * Access DEV articles, comments and other resources via API
 *
 * API version: 0.5.9
 * Contact: yo@dev.to
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package devto

// ArticleOrganization The organization the article belongs to
type ArticleOrganization struct {
	Name     string `json:"name,omitempty"`
	Username string `json:"username,omitempty"`
	Slug     string `json:"slug,omitempty"`
	// Profile image (640x640)
	ProfileImage string `json:"profile_image,omitempty"`
	// Profile image (90x90)
	ProfileImage90 string `json:"profile_image_90,omitempty"`
}
